import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import { Raleway } from 'next/font/google';

const raleway = Raleway({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-raleway',
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// import shared components
import { Navbar } from '@/components/Navbar';
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={raleway.className}>
                <Navbar>{children}</Navbar>
            </body>
        </html>
    );
}
